### ISSUE TITLE
Make tgstation/FastDMM standalone

### ISSUE THREAD

**Issue by Rockdtben** [tgstation/FastDMM#18]
@KorPhaeron Can you PM me your github email address on tgstation or discord so I can forward you an email from github support and have you approve the following change to make FastDMM owned by tgstation.

"If you'd like tgstation/FastDMM to be standalone and the root of this network we'll need permission from an owner of the tgstation organisation to do that."

**Comment by KorPhaeron** [comment]
sent on the forums

**Comment by Rockdtben** [comment]
@KorPhaeron Email sent

**Comment by KorPhaeron** [comment]
Replied

**Comment by Rockdtben** [comment]
@KorPhaeron @MrStonedOne We standalone network now.
