### ISSUE TITLE
Undo & Redo binds don't work

### ISSUE THREAD

**Issue by praisenarsie** [tgstation/FastDMM#21]
Version: 0.7.2

they worked in 0.7.1

@Rockdtben

**Comment by Rockdtben** [comment]
@praisenarsie I tested using the capsule built by the latest code, I tested by running the code, and I tested by running the 0.7.2 capsule in the Release.

I can't repro this.

**Comment by praisenarsie** [comment]
Fuck it does work, I think I've been pressing the wrong key like Ctrl X or something this whole time.
