### ISSUE TITLE
Java Errors

### ISSUE THREAD

**Issue by Chewyyy** [tgstation/FastDMM#25]
I am getting java errors whenever I try to launch my environment.  Someone suggested I might be missing a #include.  I have been looking around, is there a lib file I am suppose to add to my source or something to use FastDMM?

**Comment by Chewyyy** [comment]
https://gyazo.com/e2d457ece4833165cd4aa1e6073e8518

**Comment by Rockdtben** [comment]
@Chewyyy Let me know if this resolves your issue.

**Comment by Rockdtben** [comment]
I'll have to make a new jar file which I can get to sometime this weekend.

**Comment by Chewyyy** [comment]
Just let me know when the new jar file is made and I’ll test it out. 

I know that I took the lib files out, and made the their own dm file. I don’t get java errors, and the application shows a progress bar as it is trying to open the enviroment, and then nothing happens after it finishes loading.
